server:
 port: 8081
spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://211.232.75.41:5433/tdx_db
    username: tdx_user
    password: tdx_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    show-sql: true
mybatis:
  type-aliases-package: com.opendev.odata.domain.table
  mapper-locations: classpath:mappers/**/*.xml