server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olingo?useSSL=false&serverTimezone=UTC
    username: root
    password: <NEED_TO_INPUT>
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
